services:

  database:
    container_name: dizi-izi-database
    image: postgis/postgis:17-3.5
    volumes:
      - dizi_postgres_dev:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 5s
      timeout: 5s
      retries: 5
    entrypoint: ["/bin/sh", "-c", "docker-entrypoint.sh postgres & sleep 10 && psql -U admin -d $POSTGRES_DB -c 'CREATE EXTENSION IF NOT EXISTS postgis;' && wait"]

  backend:
    container_name: dizi-izi-backend
    image: diziizi/dizi-izi-backend:latest
    build: .
    restart: always
    ports:
      - "80:8000"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
#    uncomment for develop mode
#    volumes:
#      - ./:/app

volumes:
  dizi_postgres_dev:
